[package]
name = "ff-log-cli"
version = "0.1.0"
edition = "2024"
authors = ["Gorka Hernandez <info@gorkahernandez.com>"]

[dependencies]
clap = { version = "4.5.41", features = ["derive"] }

[dev-dependencies]
tempfile = "3.8"
