use clap::{Parser, Subcommand};
use std::fs::read_dir;
use std::io;
use std::path::Path;
use std::time::Instant;

mod commands;

fn main() -> Result<(), io::Error> {
    let start = Instant::now();

    #[cfg(unix)]
    let app_data = std::env::var("HOME").expect("No HOME directory");
    #[cfg(windows)]
    let app_data = std::env::var("APPDATA").expect("No APP_DATA directory");

    let config = Config::parse();

    let mut fflogs_dir = match &config.command {
        Command::List { fflogs_dir } => fflogs_dir.clone(),
        Command::Delete { fflogs_dir } => fflogs_dir.clone(),
        Command::Backup { fflogs_dir } => fflogs_dir.clone(),
        Command::View { fflogs_dir } => fflogs_dir.clone(),
    };

    if fflogs_dir == "default" {
        fflogs_dir = format!("{app_data}\\Advanced Combat Tracker\\FFXIVLogs");
    }

    let path = Path::new(&fflogs_dir);
    if !path.is_dir() {
        println!("Not a valid directory: {}", path.display());
        return Err(io::Error::new(
            io::ErrorKind::InvalidInput,
            "not a valid directory",
        ));
    }
    match config.command {
        Command::View { .. } => {
            commands::view::view_log_files(path)?;
        }
        _ => {
            for entry in read_dir(path)? {
                let entry = entry?;
                let path = entry.path();
                if path.is_dir() {
                    println!("Ignoring path as it is a directory: {}", path.display());
                } else {
                    match config.command {
                        Command::List { .. } => {
                            commands::list::list_log_file(&path);
                        }
                        Command::Backup { .. } => {
                            commands::backup::backup_log_file(&path);
                        }
                        Command::Delete { .. } => {
                            commands::delete::delete_log_file(&path);
                        }
                        Command::View { .. } => unreachable!(),
                    }
                }
            }
        }
    }
    let duration = start.elapsed();
    println!("Completed in: {duration:?}");
    Ok(())
}

#[derive(Parser)]
#[command(name = "ff-log-cli")]
#[command(
    about = "A CLI tool for managing Final Fantasy XIV log files generated by Advanced Combat Tracker (ACT)"
)]
#[command(
    long_about = "ff-log-cli helps you manage Final Fantasy XIV combat log files from ACT.\n\nSupported operations:\n  • List log files in a directory\n  • Backup log files to a 'bak/' subdirectory\n  • Delete log files permanently\n  • View log file contents interactively\n\nUse 'default' as the directory to auto-detect the ACT log folder location."
)]
#[command(version)]
struct Config {
    #[command(subcommand)]
    command: Command,
}

#[derive(Subcommand)]
enum Command {
    /// List all log files in the specified directory
    ///
    /// This command displays all log files found in the target directory.
    /// Use this to see what log files are available before performing
    /// backup or delete operations.
    ///
    /// Examples:
    ///   ff-log-cli list
    ///   ff-log-cli list --fflogs-dir "C:\ACT\Logs"
    ///   ff-log-cli list -f "/home/user/ACT/Logs"
    List {
        /// Directory containing FFXIV log files (use "default" for auto-detection)
        ///
        /// Specify the path to your ACT log directory, or use "default" to
        /// automatically detect the standard ACT installation location:
        /// - Windows: %APPDATA%\Advanced Combat Tracker\FFXIVLogs
        /// - Unix: $HOME/Advanced Combat Tracker/FFXIVLogs
        #[arg(
            short,
            long,
            default_value = "default",
            help = "Path to log directory or 'default' for auto-detection"
        )]
        fflogs_dir: String,
    },
    /// Permanently delete all log files in the specified directory
    ///
    /// WARNING: This operation cannot be undone! All log files in the
    /// target directory will be permanently removed from your system.
    /// Consider using the 'backup' command first to create copies.
    ///
    /// Examples:
    ///   ff-log-cli delete
    ///   ff-log-cli delete --fflogs-dir "C:\ACT\Logs"
    Delete {
        /// Directory containing FFXIV log files (use "default" for auto-detection)
        ///
        /// Specify the path to your ACT log directory, or use "default" to
        /// automatically detect the standard ACT installation location.
        #[arg(
            short,
            long,
            default_value = "default",
            help = "Path to log directory or 'default' for auto-detection"
        )]
        fflogs_dir: String,
    },
    /// Move log files to a backup directory (creates 'bak/' subdirectory)
    ///
    /// This command safely moves all log files to a 'bak/' subdirectory
    /// within the source directory. The backup directory is created
    /// automatically if it doesn't exist. This is the recommended way
    /// to archive old logs while keeping them accessible.
    ///
    /// Examples:
    ///   ff-log-cli backup
    ///   ff-log-cli backup --fflogs-dir "C:\ACT\Logs"
    Backup {
        /// Directory containing FFXIV log files (use "default" for auto-detection)
        ///
        /// Specify the path to your ACT log directory, or use "default" to
        /// automatically detect the standard ACT installation location.
        #[arg(
            short,
            long,
            default_value = "default",
            help = "Path to log directory or 'default' for auto-detection"
        )]
        fflogs_dir: String,
    },
    /// Interactively view log file contents
    ///
    /// This command presents a numbered list of all log files in the
    /// directory and allows you to select one to view its contents.
    /// Perfect for quickly inspecting log files before deciding what
    /// to do with them.
    ///
    /// Examples:
    ///   ff-log-cli view
    ///   ff-log-cli view --fflogs-dir "C:\ACT\Logs"
    View {
        /// Directory containing FFXIV log files (use "default" for auto-detection)
        ///
        /// Specify the path to your ACT log directory, or use "default" to
        /// automatically detect the standard ACT installation location.
        #[arg(
            short,
            long,
            default_value = "default",
            help = "Path to log directory or 'default' for auto-detection"
        )]
        fflogs_dir: String,
    },
}

#[cfg(test)]
mod tests {
    use super::*;
    use clap::Parser;
    use std::fs::File;
    use std::io::Write;
    use tempfile::TempDir;

    #[test]
    fn test_config_list_command() {
        let args = ["program", "list"];
        let config = Config::try_parse_from(args).unwrap();

        assert!(matches!(config.command, Command::List { .. }));
        if let Command::List { fflogs_dir } = config.command {
            assert_eq!(fflogs_dir, "default");
        }
    }

    #[test]
    fn test_config_backup_command() {
        let args = ["program", "backup"];
        let config = Config::try_parse_from(args).unwrap();

        assert!(matches!(config.command, Command::Backup { .. }));
        if let Command::Backup { fflogs_dir } = config.command {
            assert_eq!(fflogs_dir, "default");
        }
    }

    #[test]
    fn test_config_delete_command() {
        let args = ["program", "delete"];
        let config = Config::try_parse_from(args).unwrap();

        assert!(matches!(config.command, Command::Delete { .. }));
        if let Command::Delete { fflogs_dir } = config.command {
            assert_eq!(fflogs_dir, "default");
        }
    }

    #[test]
    fn test_config_view_command() {
        let args = ["program", "view"];
        let config = Config::try_parse_from(args).unwrap();

        assert!(matches!(config.command, Command::View { .. }));
        if let Command::View { fflogs_dir } = config.command {
            assert_eq!(fflogs_dir, "default");
        }
    }

    #[test]
    fn test_config_with_custom_directory() {
        let args = ["program", "list", "--fflogs-dir", "/path/to/logs"];
        let config = Config::try_parse_from(args).unwrap();

        assert!(matches!(config.command, Command::List { .. }));
        if let Command::List { fflogs_dir } = config.command {
            assert_eq!(fflogs_dir, "/path/to/logs");
        }
    }

    #[test]
    fn test_config_with_short_flag() {
        let args = ["program", "list", "-f", "/path/to/logs"];
        let config = Config::try_parse_from(args).unwrap();

        assert!(matches!(config.command, Command::List { .. }));
        if let Command::List { fflogs_dir } = config.command {
            assert_eq!(fflogs_dir, "/path/to/logs");
        }
    }

    #[test]
    fn test_config_with_spaces_in_path() {
        let args = ["program", "list", "--fflogs-dir", "/path/with spaces/logs"];
        let config = Config::try_parse_from(args).unwrap();

        if let Command::List { fflogs_dir } = config.command {
            assert_eq!(fflogs_dir, "/path/with spaces/logs");
        }
    }

    #[test]
    fn test_config_default_directory() {
        let args = ["program", "list"];
        let config = Config::try_parse_from(args).unwrap();

        if let Command::List { fflogs_dir } = config.command {
            assert_eq!(fflogs_dir, "default");
        }
    }

    #[test]
    fn test_command_enum_variants() {
        let list_cmd = Command::List {
            fflogs_dir: "default".to_string(),
        };
        let backup_cmd = Command::Backup {
            fflogs_dir: "default".to_string(),
        };
        let delete_cmd = Command::Delete {
            fflogs_dir: "default".to_string(),
        };
        let view_cmd = Command::View {
            fflogs_dir: "default".to_string(),
        };

        assert!(matches!(list_cmd, Command::List { .. }));
        assert!(matches!(backup_cmd, Command::Backup { .. }));
        assert!(matches!(delete_cmd, Command::Delete { .. }));
        assert!(matches!(view_cmd, Command::View { .. }));
    }

    #[test]
    fn test_config_invalid_command_fails() {
        let args = ["program", "invalid"];
        let result = Config::try_parse_from(args);

        assert!(result.is_err());
    }

    #[test]
    fn test_config_no_command_fails() {
        let args = ["program"];
        let result = Config::try_parse_from(args);

        assert!(result.is_err());
    }

    #[test]
    fn test_main_function_with_valid_directory() {
        let temp_dir = TempDir::new().unwrap();

        let test_file = temp_dir.path().join("test.log");
        let mut file = File::create(&test_file).unwrap();
        writeln!(file, "test log content").unwrap();

        let args = [
            "program",
            "list",
            "--fflogs-dir",
            &temp_dir.path().to_string_lossy(),
        ];
        let config = Config::try_parse_from(args).unwrap();

        assert!(matches!(config.command, Command::List { .. }));
        if let Command::List { fflogs_dir } = config.command {
            assert_eq!(fflogs_dir, temp_dir.path().to_string_lossy());
        }
    }
}
